# Generated by Django 3.2 on 2022-01-05 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webrtc', '0002_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Participants',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='participants_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
